[project]
name = "cp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=44.0.2",
    "jupyter>=1.1.1",
    "plotly>=6.0.1",
    "requests>=2.32.3",
    "scapy>=2.6.1",
]
