services:
  postgres:
    image: postgres:16
    container_name: postgres_lab
    environment:
      POSTGRES_DB: labdb
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpassword
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - ./db_init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
