services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
